/* wickra-embed no-alloc C ABI — generated by cbindgen; do not edit by hand. */

#ifndef WICKRA_EMBED_H
#define WICKRA_EMBED_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Success return from an `init` call.
#define WICKRA_EMBED_OK 0

// An `update` produced a value (written into `out`).
#define WICKRA_EMBED_READY 1

// An `update` is still warming up; `out` is untouched.
#define WICKRA_EMBED_WARMUP 0

// A required pointer argument was null.
#define WICKRA_EMBED_ERR_NULL -1

// An input price/OHLC value was NaN or infinite.
#define WICKRA_EMBED_ERR_NONFINITE -2

// An `ema` init was asked for a zero period.
#define WICKRA_EMBED_ERR_PERIOD -3

// An opaque, caller-allocated ATR(14) handle.
typedef struct WickraAtr WickraAtr;

// An opaque, caller-allocated EMA handle. Its size is independent of the period
// (an EMA keeps no window), so one buffer size serves every period.
typedef struct WickraEma WickraEma;

// An opaque, caller-allocated ROC(10) handle.
typedef struct WickraRoc WickraRoc;

// An opaque, caller-allocated RSI(14) handle.
typedef struct WickraRsi WickraRsi;

// An opaque, caller-allocated SMA(20) handle. Place a buffer of
// [`wickra_sma_size`] bytes at [`wickra_sma_align`] alignment and `init` into it.
typedef struct WickraSma WickraSma;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// The library version as a static, NUL-terminated C string. Valid in `no_std`.
const char *wickra_embed_version(void);

// Bytes of caller storage a [`WickraSma`] handle needs on this target.
uintptr_t wickra_sma_size(void);

// Alignment (bytes) a [`WickraSma`] handle needs on this target.
uintptr_t wickra_sma_align(void);

// Initialise a fresh SMA(20) into caller storage. `handle` must point to
// [`wickra_sma_size`] bytes, [`wickra_sma_align`]-aligned.
int wickra_sma_init(WickraSma *handle);

// Feed one price. Writes the average into `*out` and returns
// [`WICKRA_EMBED_READY`] once warm, else [`WICKRA_EMBED_WARMUP`].
int wickra_sma_update(WickraSma *handle, double input, double *out);

// Reset the handle to its freshly-initialised state. Null-safe.
void wickra_sma_reset(WickraSma *handle);

// Number of inputs before the first value. Null-safe (returns 0).
uintptr_t wickra_sma_warmup(const WickraSma *handle);

// 1 if the next update will yield a value, else 0. Null-safe.
int wickra_sma_is_ready(const WickraSma *handle);

// Bytes of caller storage a [`WickraEma`] handle needs on this target.
uintptr_t wickra_ema_size(void);

// Alignment (bytes) a [`WickraEma`] handle needs on this target.
uintptr_t wickra_ema_align(void);

// Initialise a fresh EMA of the given `period` into caller storage. Returns
// [`WICKRA_EMBED_ERR_PERIOD`] if `period == 0`.
int wickra_ema_init(WickraEma *handle, uintptr_t period);

// Feed one price. See [`wickra_sma_update`] for the return contract.
int wickra_ema_update(WickraEma *handle, double input, double *out);

// Reset the handle. Null-safe. The period set at `init` is preserved.
void wickra_ema_reset(WickraEma *handle);

// Number of inputs before the first value. Null-safe (returns 0).
uintptr_t wickra_ema_warmup(const WickraEma *handle);

// 1 if the next update will yield a value, else 0. Null-safe.
int wickra_ema_is_ready(const WickraEma *handle);

// Bytes of caller storage a [`WickraRsi`] handle needs on this target.
uintptr_t wickra_rsi_size(void);

// Alignment (bytes) a [`WickraRsi`] handle needs on this target.
uintptr_t wickra_rsi_align(void);

// Initialise a fresh RSI(14) into caller storage.
int wickra_rsi_init(WickraRsi *handle);

// Feed one price. See [`wickra_sma_update`] for the return contract.
int wickra_rsi_update(WickraRsi *handle, double input, double *out);

// Reset the handle. Null-safe.
void wickra_rsi_reset(WickraRsi *handle);

// Number of inputs before the first value. Null-safe (returns 0).
uintptr_t wickra_rsi_warmup(const WickraRsi *handle);

// 1 if the next update will yield a value, else 0. Null-safe.
int wickra_rsi_is_ready(const WickraRsi *handle);

// Bytes of caller storage a [`WickraAtr`] handle needs on this target.
uintptr_t wickra_atr_size(void);

// Alignment (bytes) a [`WickraAtr`] handle needs on this target.
uintptr_t wickra_atr_align(void);

// Initialise a fresh ATR(14) into caller storage.
int wickra_atr_init(WickraAtr *handle);

// Feed one OHLC bar. The four prices must all be finite (else
// [`WICKRA_EMBED_ERR_NONFINITE`]). Volume and timestamp do not affect ATR and
// are not part of the signature.
int wickra_atr_update(WickraAtr *handle,
                      double open,
                      double high,
                      double low,
                      double close,
                      double *out);

// Reset the handle. Null-safe.
void wickra_atr_reset(WickraAtr *handle);

// Number of candles before the first value. Null-safe (returns 0).
uintptr_t wickra_atr_warmup(const WickraAtr *handle);

// 1 if the next update will yield a value, else 0. Null-safe.
int wickra_atr_is_ready(const WickraAtr *handle);

// Bytes of caller storage a [`WickraRoc`] handle needs on this target.
uintptr_t wickra_roc_size(void);

// Alignment (bytes) a [`WickraRoc`] handle needs on this target.
uintptr_t wickra_roc_align(void);

// Initialise a fresh ROC(10) into caller storage.
int wickra_roc_init(WickraRoc *handle);

// Feed one price. See [`wickra_sma_update`] for the return contract.
int wickra_roc_update(WickraRoc *handle, double input, double *out);

// Reset the handle. Null-safe.
void wickra_roc_reset(WickraRoc *handle);

// Number of inputs before the first value. Null-safe (returns 0).
uintptr_t wickra_roc_warmup(const WickraRoc *handle);

// 1 if the next update will yield a value, else 0. Null-safe.
int wickra_roc_is_ready(const WickraRoc *handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WICKRA_EMBED_H */
